##
#    Copyright (C) 2015 Brandon Schlueter
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

# Rubocop's default of 15 is far too low for even database connections
Metrics/AbcSize:
  Max: 20

# Rubocop's default is 80, which is overly restrictive (the author likes long variable names)
Metrics/LineLength:
  Max: 100

# The default of 10 is quite restrictive
Metrics/MethodLength:
  Max: 20

# The author started with python, so prefers this:
Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
